export const CLICK_MODAL_TYPE = "CLICK_MODAL_TYPE";
export const LOGIN = "LOGIN";
export const SHOW_MODAL = "SHOW_MODAL";
export const LOGIN_USER_INFO = "LOGIN_USER_INFO";
export const USER_LOCATION = "USER_LOCATION";
export const USER_ADDRESS = "USER_ADDRESS";
export const CAFE_LIST_COUNT = "CAFE_LIST_COUNT";
export const CAFE_LIST_COUNT_RESET = "CAFE_LIST_COUNT_RESET";
export const CAFE_LIST_CATEGORY = "CAFE_LIST_CATEGORY";
export const CAFE_LIST_COUNT_HASH = "CAFE_LIST_COUNT_HASH";
//thunk
export const GET_CAFE_INFO_REQUEST = "GET_CAFE_INFO_REQUEST";
export const GET_CAFE_INFO_SUCCESS = "GET_CAFE_INFO_SUCCESS";
export const GET_CAFE_INFO_FAILURE = "GET_CAFE_INFO_FAILURE";
export const GET_CAFE_HASHTAGS_SUCCESS = "GET_CAFE_HASHTAGS_SUCCESS";
export const ADD_LIKE = "ADD_LIKE";
export const ADD_HASH = "ADD_HASH";
