export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const USER_LOCATION = "USER_LOCATION";
export const CAFE_LIST_COUNT = "CAFE_LIST_COUNT";
export const CAFE_LIST_COUNT_RESET = "CAFE_LIST_COUNT_RESET";
export const CAFE_LIST_CATEGORY = "CAFE_LIST_CATEGORY";
export const CAFE_LIST_COUNT_HASH = "CAFE_LIST_COUNT_HASH";
